before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: ggMPcxBP53EG6aX6Ok3CUfrABNljUObVq6BXeNqKcOYHg+KHO/0zYDhIOjNutgw2fdFDtdNI/o1RamWeZY97yr136aRGpYvYSIKyI7RatnDsE6VZNaXAIaFuTJecagDYD+xSvkNl0+Pl8zYtg15Wx1R9TrXX40jukeeU2mtbJqjDP3u4VOPuJNLRGA+G0iukzafFHJAqWbmNGgZym2pixM7g+IR+v4siwV4CIB6KpQiXCp9Ad+5Pkylc5q+sXmuIOojU1mkIkPEpK+mYLSC2KG3upkdxZKHtZ0PMOYpvtJl53trdBcQqDY3JRt+nWAzAUY18FLhAgZtLJBHFdpJlG7amUx6+DqgY8RoVkUJRkf92cxdMEwvSbCwJd4HNbdgoeWYka5BXMnB0mF/k8UUKQxdws6FH/jTCEiykGu2ujuiMZvRSULhTcDgQRo6mN/djvv86oqj2DwgJhQU9znjblkV7wNRaoOD/PFOFzHfdqGso5uaJTT8HGlnPKfJMSVp+8tXvwwGet27BMhssgRejk4R+yC9Q/fDQBYSBkcdFQYvtb5PWCoI7kVgXQkByOsauD8Q1MXQnX+hmDnk+xuGkj4KuYK2VOimYFXolcqjfRc1leAtdzbKw/NzllJi3uWjlZUkQD+SbCvi5bGbjRsrk8HB27fOQC/6gPdwkGTugHaU= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
